version: '2'

services:
  aggregator:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./aggregator:/libre/aggregator
      - ./api:/libre/api
      - ./customer:/libre/customer
      - ./sale:/libre/sale
      - ./broker:/libre/broker
      - ./insurer:/libre/insurer
    #command: bash -c "python manage.py makemigrations && \
    #         python manage.py migrate && \
    #         python manage.py runserver 0.0.0.0:8080"
