version: '2'

services:
  aggregator:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 5000:8000
    volumes:
      - ./aggregator:/aggregator
