# Generated by Django 2.1.7 on 2019-02-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
    ]
