# Generated by Django 2.1.7 on 2019-02-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190216_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cellphone',
            field=models.CharField(default='(00) 99999-9999', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='name@email.com', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='facebook',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram',
            field=models.CharField(default='@name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
