# Generated by Django 2.1.7 on 2019-02-16 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190216_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='customer',
            name='signupdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='customer', max_length=100),
        ),
    ]
