# Generated by Django 2.1.7 on 2019-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='api',
            field=models.CharField(default='api.insurer.site.com', max_length=300),
        ),
        migrations.AddField(
            model_name='insurer',
            name='site',
            field=models.CharField(default='insurer.site.com', max_length=300),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='name',
            field=models.CharField(default='insurer', max_length=100),
        ),
    ]
