# Generated by Django 2.1.7 on 2019-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='share',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sale',
            name='totalvalue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(default='sale', max_length=100),
        ),
    ]
