# Generated by Django 2.1.7 on 2019-02-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20190216_1229'),
        ('sale', '0002_auto_20190216_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='broker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='broker.Broker'),
        ),
    ]
