# Generated by Django 2.1.7 on 2019-02-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20190216_1214'),
        ('sale', '0003_sale_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='Customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
        ),
    ]
