# Generated by Django 2.1.7 on 2019-02-16 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='enddate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sale',
            name='paymentdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sale',
            name='startdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
